---
- name: Escalar deployment en Kubernetes
  hosts: vm_kubernetes
  become: yes  # Permite ejecutar las tareas con privilegios de sudo
  gather_facts: no
  tasks:
    - name: Escalar el deployment
      kubernetes.core.k8s:
        name: my-app
        namespace: default  # o el namespace correspondiente
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          spec:
            replicas: 0 #manualmente se puede poner las replicas 
        kubeconfig: /home/fhygonenq/.kube/config
      register: result  # Almacena el resultado de la tarea

    - name: Mostrar el resultado del escalado
      debug:
        var: result
