apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP  # Se puede usar NodePort en caso de necesitar acceso desde fuera del clúster
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
