version: '3.1'

services:
  opencart:
    image: bitnami/opencart
    ports:
      - "8888:8080"
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_ROOT_PASSWORD=bitnami
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_PASSWORD=bitnami
      - OPENCART_DATABASE_NAME=opencart_db
    depends_on:
      - mariadb

  mariadb:
    image: bitnami/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=bitnami
      - MARIADB_USER=bn_opencart
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=opencart_db
