---
- name: Crear el archivo composer.json en el contenedor Docker
  shell: |
    docker exec -u root -w /bitnami/opencart_storage {{ hostvars[inventory_hostname].nombre_contenedor }} \
    bash -c 'echo "{
      \"require\": {
        \"aws/aws-crt-php\": \"^1.0\",
        \"aws/aws-sdk-php\": \"^3.0\",
        \"guzzlehttp/guzzle\": \"^7.0\",
        \"guzzlehttp/promises\": \"^1.0\",
        \"guzzlehttp/psr7\": \"^2.0\",
        \"mtdowling/jmespath.php\": \"^2.0\",
        \"psr/http-client\": \"^1.0\",
        \"psr/http-factory\": \"^1.0\",
        \"psr/http-message\": \"^1.0\",
        \"psr/log\": \"^1.0\",
        \"ralouphie/getallheaders\": \"^3.0\",
        \"scssphp/scssphp\": \"^1.0\",
        \"symfony/deprecation-contracts\": \"^2.0\",
        \"symfony/polyfill-ctype\": \"^1.8\",
        \"symfony/polyfill-mbstring\": \"^1.8\",
        \"twig/twig\": \"^3.7\"
      }
    }" > /bitnami/opencart_storage/composer.json'

- name: Verificar la existencia de composer.json en el contenedor Docker
  shell: docker exec -u root {{ hostvars[inventory_hostname].nombre_contenedor }}  ls -l /bitnami/opencart_storage
  register: ls_output

- name: Mostrar la salida de ls
  debug:
    var: ls_output.stdout

- name: Ejecutar composer update en el contenedor Docker
  shell: docker exec -u root -w /bitnami/opencart_storage {{ hostvars[inventory_hostname].nombre_contenedor }}  composer update
  register: composer_update_output
  ignore_errors: yes

- name: Mostrar la salida de composer update
  debug:
    var: composer_update_output.stdout

- name: Ejecutar composer install en el contenedor Docker
  shell: docker exec -u root -w /bitnami/opencart_storage {{ hostvars[inventory_hostname].nombre_contenedor }}  composer install
  register: composer_install_output
  ignore_errors: yes

- name: Mostrar la salida de composer install
  debug:
    var: composer_install_output.stdout

- name: Hacer accesible el archivo de dependencias
  shell: docker exec -u root -w /bitnami/opencart_storage {{ hostvars[inventory_hostname].nombre_contenedor }} \
    chmod 755 /bitnami/opencart_storage/vendor
